title: Ji Home Page
description: Ji language is an abstract symbolic programmig language
logo: https://github.com/pages-themes/minimal/raw/master/thumbnail.png
show_downloads: true
google_analytics: XYZ
